name: Continuous integration

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 18 * * *'

env:
  LIB: x509_lint

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.74.0
          - nightly
        manifest:
          - Cargo.toml
          - x509_lint/Cargo.toml
        features:
          - ""
          - --all-features
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cargo update (fix for MSRV)
        run: cargo update -p time --precise 0.3.41
        if: matrix.rust == '1.74.0'
      - run: RUSTFLAGS="-D warnings" cargo check --locked --manifest-path ${{ matrix.manifest }} ${{ matrix.features }}

  test:
    name: Test Suite
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  test_features:
    name: Test suite (with features)
    needs: check-all-features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - --no-default-features
          - --all-features
        manifest:
          - Cargo.toml
          - x509_lint/Cargo.toml
    steps:
      - uses: actions/checkout@v5
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo test --locked --manifest-path ${{ matrix.manifest }} ${{ matrix.features }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - Cargo.toml
          - x509_lint/Cargo.toml
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy --manifest-path ${{ matrix.manifest }} --all-features -- -D warnings

  doc:
    name: Build documentation
    needs: check
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: --cfg docsrs
    strategy:
      matrix:
        manifest:
          - Cargo.toml
          - x509_lint/Cargo.toml
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo doc --manifest-path ${{ matrix.manifest }} --no-deps --all-features

  semver:
    name: Check semver compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: x509_lint/Cargo.toml
